apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlogic-operator
  namespace: system
  labels:
    control-plane: kuberlogic-operator
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: IMG_REPO
              value: quay.io/kuberlogic
            - name: IMG_PULL_SECRET
              value: ""
            - name: SENTRY_DSN
              value: https://369afa8d72cb4772b46936f7291218b7@kl.sentry.cloudlinux.com/2
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GRAFANA_ENABLED
              value: "true"
            - name: GRAFANA_ENDPOINT
              value: http://grafana:3000/
        - name: apiserver
          env:
            - name: KUBERLOGIC_AUTH_PROVIDER
              value: keycloak
            - name: KUBERLOGIC_AUTH_KEYCLOAK_CLIENTID
              value: apiserver
            - name: KUBERLOGIC_AUTH_KEYCLOAK_CLIENT_SECRET
              value: apiserver-secret
            - name: KUBERLOGIC_AUTH_KEYCLOAK_REALM_NAME
              value: kuberlogic_realm
            - name: KUBERLOGIC_AUTH_KEYCLOAK_URL
              value: https://keycloak:8443
            - name: SENTRY_DSN
              value: https://3fc53cea3e0045aab42cc8e5358d6264@kl.sentry.cloudlinux.com/4
            - name: KUBERLOGIC_DEBUGLOGS
              value: "true"
