apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: apiserver
  newName: quay.io/kuberlogic/apiserver
  newTag: 0.0.18
- name: controller
  newName: quay.io/kuberlogic/operator
  newTag: 0.0.19-AP-3
patchesStrategicMerge:
- regcred.yaml
resources:
- operator.yaml
- service.yaml
