apiVersion: v1
data:
  config.js: |
    let configApiUrl = '{{ .Values.config.apiEndpoint }}/api/v1';
    let monitoringConsoleUrl = '{{ .Values.config.monitoringConsoleEndpoint }}';
    let helpUrl = '{{ .Values.config.helpEndpoint }}';
kind: ConfigMap
metadata:
  name: "{{ include "kuberlogic-ui.fullname" . }}"
  namespace: {{ .Release.Namespace }}
