---
# Target deployment platform for Kuberlogic
# Currently supported:
#   * `aws` (Amazon Web Services)
#   * `generic` (Any other Kubernetes installation. Default.)
platform: generic
# Whether to enable debug logs or not
debugLogs: true
# Provides an absolute path to a kubeconfig file
# default is $HOME/.kube/config
# kubeconfigPath: /path/to/kubeconfig

# namespace where Kuberlogic components will be installed
namespace: kuberlogic

# container registry connection settings. omit for public access
# registry:
#   server: https://quay.io
#   username: quayusername
#   password: quaypassword

# connection endpoints configuration. These endpoints will be used to configure Kuberlogic endpoints
# and it is expected that Kuberlogic ingress traffic will be received via these endpoints
endpoints:
  api: kuberlogic.com
  ui: kuberlogic.com
  monitoringConsole: mc.kuberlogic.com

# `auth` section contains settings for Keycloak-based authentication
auth:
  # demoUserPassword configures a password for Kuberlogic test user: user@kuberlogic.com
  demoUserPassword: secret
  # adminPassword is password for Keycloak realm administrator: `kuberlogic`
  adminPassword: adminPassword
