---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: "kuberlogic-alertmanager"
  name: kuberlogic-alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/alertmanager-rules.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "kuberlogic-alertmanager"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "kuberlogic-alertmanager"
    spec:
      containers:
        - image: {{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
          name: alertmanager
          ports:
            - containerPort: {{ .Values.alertmanager.port }}
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yml
              name: alertmanager-config
              subPath: alertmanager.yml
        - image: {{ .Values.alertreceiver.image.repository }}:{{ .Values.alertreceiver.image.tag }}
          name: kuberlogic-alerting
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - configMap:
            name: {{ .Values.alertmanager.configmap }}
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: kuberlogic-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: alertui
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app.kubernetes.io/name: "kuberlogic-alertmanager"
