---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "monitoring.labels" .  | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlogic-victoriametrics
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: kuberlogic-victoriametrics
      {{- include "monitoring.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kuberlogic-victoriametrics
        {{- include "monitoring.labels" . | nindent 8 }}
    spec:
      containers:
        - name: vmalert
          image: {{ .Values.victoriametrics.vmalert.image.repository }}:{{ .Values.victoriametrics.vmalert.image.tag }}
          args:
            - -datasource.url=http://localhost:{{ .Values.victoriametrics.vmserver.port }}
            - -remoteWrite.url=http://localhost:{{ .Values.victoriametrics.vmserver.port }}
            - -remoteRead.url=http://localhost:{{ .Values.victoriametrics.vmserver.port }}
            - -notifier.url=http://{{ .Values.alertmanager.service.name }}:{{ .Values.alertmanager.service.port }}
            - -rule=/etc/vmalert/alert.rules
          volumeMounts:
            - mountPath: /etc/vmalert
              name: vmalert-rules-volume
          terminationMessagePath: /dev/termaniation-log
          terminationMessagePolicy: File
        - args:
            - -httpListenAddr=:{{ .Values.victoriametrics.vmserver.port }}
            - -promscrape.config=/etc/config/victoriametrics.yaml
            - -storageDataPath=/data
          image: {{ .Values.victoriametrics.vmserver.image.repository }}:{{ .Values.victoriametrics.vmserver.image.tag }}
          name: vmserver
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
              readOnly: true
            - mountPath: /data
              name: data-volume
          ports:
            - containerPort: {{ .Values.victoriametrics.vmserver.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ .Values.victoriametrics.vmserver.port }}
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: {{ .Values.victoriametrics.serviceAccount.name }}
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      terminationGracePeriodSeconds: 300
      volumes:
        - configMap:
            defaultMode: 420
            name: victoriametrics-config
          name: config-volume
        - name: data-volume
          persistentVolumeClaim:
            claimName: victoriametrics-data
        - configMap:
            defaultMode: 420
            name: vmalert-rules
          name: vmalert-rules-volume
---
apiVersion: v1
kind: Service
metadata:
  name: kuberlogic-victoriametrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.victoriametrics.service.port }}
      protocol: TCP
      targetPort: {{ .Values.victoriametrics.vmserver.port }}
  selector:
    app.kubernetes.io/component: kuberlogic-victoriametrics
  type: LoadBalancer
