apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: mysql-operator
    newName: quay.io/kuberlogic/mysql-operator
    newTag: latest
patchesStrategicMerge:
  - patches/regcred.yaml
resources:
  - operator-service-account-rbac.yaml
  - orc-secret.yaml
  - orc-config.yaml
  - orc-service.yaml
  - statefulset.yaml

