apiVersion: v1
appVersion: "2.5"
description: The Cloud-Native Ingress and API-management
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- email: harry@konghq.com
  name: hbagdi
- email: traines@konghq.com
  name: rainest
name: kong
version: 2.3.0
