
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: kuberlogicalerts.kuberlogic.com
spec:
  group: kuberlogic.com
  names:
    kind: KuberLogicAlert
    listKind: KuberLogicAlertList
    plural: kuberlogicalerts
    shortNames:
    - kla
    singular: kuberlogicalert
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The cluster status
      jsonPath: .status.status
      name: Status
      type: string
    - description: Alert name
      jsonPath: .spec.alertname
      name: AlertName
      type: string
    - description: Alert value
      jsonPath: .spec.alertvalue
      name: AlertValue
      type: string
    - description: Cluster name
      jsonPath: .spec.cluster
      name: Cluster
      type: string
    - description: Affected Pod Name
      jsonPath: .spec.pod
      name: Pod
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              alertname:
                description: Alert name
                pattern: ^.*$
                type: string
              alertvalue:
                description: Value
                pattern: ^.*$
                type: string
              cluster:
                description: Cluster name
                pattern: ^.*$
                type: string
              pod:
                description: Pod
                pattern: ^.*$
                type: string
            required:
            - alertname
            - alertvalue
            - cluster
            - pod
            type: object
          status:
            description: KuberLogicAlert defines the observed state of KuberLogicAlert
            properties:
              status:
                type: string
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
