
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: kuberlogicbackuprestores.kuberlogic.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    description: The backup status
    name: Status
    type: string
  - JSONPath: .spec.name
    description: The cluster name
    name: Cluster name
    type: string
  - JSONPath: .spec.type
    description: The backup type
    name: Type
    type: string
  - JSONPath: .spec.backup
    description: The backup link
    name: Link
    type: string
  group: kuberlogic.com
  names:
    kind: KuberLogicBackupRestore
    listKind: KuberLogicBackupRestoreList
    plural: kuberlogicbackuprestores
    shortNames:
    - klr
    singular: kuberlogicbackuprestore
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backup:
              description: link to backup on the storage
              type: string
            database:
              description: what database need to be restored
              type: string
            name:
              description: 'Cluster name TODO: need to implement validation based
                on webhook - https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html
                it gives the ability to check cluster name is exists or not'
              type: string
            secret:
              description: credentials for storage type
              type: string
            type:
              description: Type of the backup storage
              enum:
              - s3
              type: string
          required:
          - backup
          - database
          - name
          - secret
          - type
          type: object
        status:
          description: KuberLogicBackupRestoreStatus defines the observed state of
            KuberLogicBackupRestore
          properties:
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
