apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: updater
  newName: quay.io/kuberlogic/updater
  newTag: 0.0.28

patchesStrategicMerge:
- patches/regcred.yaml
- patches/gitlab-env.yaml
resources:
- cronjob.yaml
- service-account-rbac.yaml
